# GQYOS systemd-boot 配置
default  arch.conf
timeout  10
console-mode max
editor   no

title   GQYOS Install
linux   /boot/vmlinuz-linux
initrd  /boot/amd-ucode.img
initrd  /boot/initramfs-linux.img
options cryptdevice=UUID=LABEL=GQYOS:root:allow-discards root=/dev/mapper/root rw rootfstype=btrfs

title   GQYOS Install (NVIDIA)
linux   /boot/vmlinuz-linux
initrd  /boot/amd-ucode.img
initrd  /boot/initramfs-linux.img
options cryptdevice=UUID=LABEL=GQYOS:root:allow-discards root=/dev/mapper/root rw rootfstype=btrfs nvidia-drm.modeset=1

title   GQYOS Install (Safe Mode)
linux   /boot/vmlinuz-linux
initrd  /boot/amd-ucode.img
initrd  /boot/initramfs-linux.img
options cryptdevice=UUID=LABEL=GQYOS:root:allow-discards root=/dev/mapper/root rw rootfstype=btrfs nomodeset
