# GQYOS 安装项
title   GQYOS Install
linux   /boot/vmlinuz-linux
initrd  /boot/amd-ucode.img
initrd  /boot/initramfs-linux.img
options cryptdevice=UUID=LABEL=GQYOS:root:allow-discards root=/dev/mapper/root rw rootfstype=btrfs
